"""
Module 3 - Priority Explainer

Converts the factors used by the priority engine into
human-readable explanations for the assigned priority.

This module does NOT calculate or change the priority score.
It only explains why the incident received its priority.
"""

from typing import Any


def explain_priority(
    incident: dict[str, Any],
    priority_result: dict[str, Any],
) -> list[str]:
    """
    Generate human-readable reasons for an incident's priority.

    Parameters
    ----------
    incident : dict
        Processed incident information.

    priority_result : dict
        Result returned by calculate_priority(), containing:
        - priority_score
        - priority_level
        - priority_factors

    Returns
    -------
    list[str]
        List of explanations describing why the incident
        received its priority.
    """

    if not isinstance(incident, dict):
        raise TypeError("incident must be a dictionary.")

    if not isinstance(priority_result, dict):
        raise TypeError("priority_result must be a dictionary.")

    priority_score = priority_result.get("priority_score")
    priority_level = priority_result.get("priority_level")
    priority_factors = priority_result.get("priority_factors", [])

    if priority_score is None:
        raise KeyError("priority_result must contain 'priority_score'.")

    if priority_level is None:
        raise KeyError("priority_result must contain 'priority_level'.")

    if not isinstance(priority_factors, list):
        raise TypeError("priority_factors must be a list.")

    reasons = []

    # ---------------------------------------------------------
    # Add reasons generated by the priority engine
    # ---------------------------------------------------------

    for factor in priority_factors:
        if not isinstance(factor, dict):
            continue

        reason = factor.get("reason")

        if isinstance(reason, str) and reason.strip():
            reasons.append(reason.strip())

    # ---------------------------------------------------------
    # If no specific factors contributed, provide a general
    # explanation.
    # ---------------------------------------------------------

    if not reasons:
        reasons.append(
            f"No major priority factors were reported; "
            f"incident classified as {priority_level} priority."
        )

    # ---------------------------------------------------------
    # Add overall priority explanation
    # ---------------------------------------------------------

    overall_reason = (
        f"Priority score {priority_score}/100 resulted in "
        f"{priority_level} priority."
    )

    reasons.append(overall_reason)

    return reasons


__all__ = ["explain_priority"]